// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";
import { chatCompletion, parseJsonObject, resolveAIProvider, type AISettings, type ResolvedAIProvider } from "../_shared/ai-provider.ts";
import { composeTelePostSystemPrompt } from "../_shared/prompt-composer.ts";

const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-cron-secret", "Access-Control-Allow-Methods": "POST, GET, OPTIONS, PUT, DELETE" };
const FALLBACK_MODEL = 'gemini-3.5-flash';
const TOPIC_LIBRARY = ['সিন্ধু সভ্যতা','পলাশীর যুদ্ধ','ভারতের সংবিধান','মৌলিক কর্তব্য','ভারতের নদী','ভারতের জলবায়ু','কোষ জীববিজ্ঞান','মানবদেহ','নিউটনের সূত্র','অম্ল ও ক্ষার','ভারতীয় অর্থনীতি','জিএসটি','রিজার্ভ ব্যাঙ্ক','আন্তর্জাতিক সংস্থা','ভারতীয় শিল্প ও সংস্কৃতি','মহাকাশ গবেষণা','পরিবেশ ও বাস্তুতন্ত্র','জাতীয় উদ্যান','খেলাধুলা ও পুরস্কার','কম্পিউটার সাধারণ জ্ঞান'];
async function getAISettings(supabase:any):Promise<AISettings>{const {data}=await supabase.from('system_settings').select('setting_value').eq('setting_key','ai_settings').maybeSingle();return data?.setting_value||{provider:'openrouter',model:FALLBACK_MODEL,temperature:0.7};}
function rotatedTopic(channelId:string,slotIndex:number,dayNumber:number){let hash=0;for(let i=0;i<channelId.length;i++)hash=((hash<<5)-hash+channelId.charCodeAt(i))|0;return TOPIC_LIBRARY[(Math.abs(hash)+dayNumber*12+slotIndex)%TOPIC_LIBRARY.length];}
function getLocalTime(date:Date,timeZone:string){const parts=new Intl.DateTimeFormat('en-GB',{timeZone,hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(date);return `${parts.find(p=>p.type==='hour')?.value||'00'}:${parts.find(p=>p.type==='minute')?.value||'00'}`;}
function computeScheduledDate(time:string,timeZone:string,now:Date){const [hour,minute]=time.substring(0,5).split(':').map(Number);const localDate=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now);const [localHour,localMinute]=getLocalTime(now,timeZone).split(':').map(Number);const utcMinutes=now.getUTCHours()*60+now.getUTCMinutes();let offsetMinutes=localHour*60+localMinute-utcMinutes;if(offsetMinutes>840)offsetMinutes-=1440;if(offsetMinutes<-840)offsetMinutes+=1440;const [year,month,day]=localDate.split('-').map(Number);const result=new Date(Date.UTC(year,month-1,day));result.setUTCMinutes(hour*60+minute-offsetMinutes);return result;}
function isValidQuestion(q:any){return Boolean(q?.question)&&Array.isArray(q.options)&&q.options.length===4&&Number.isInteger(q.correct_option_index)&&q.correct_option_index>=0&&q.correct_option_index<=3;}
function normalizeText(value:any){return String(value??'').trim().toLocaleLowerCase().replace(/[^\p{L}\p{N}\s]+/gu,' ').replace(/\s+/g,' ');}

async function fetchQuestionBankQuestions(supabase:any,userId:string,channelId:string,count:number,topic:string,subject?:string,language='bn'){const safe=Math.max(1,Math.min(count,50));const cleanTopic=normalizeText(topic);const cleanSubject=normalizeText(subject);if(!cleanTopic)throw new Error('A non-empty topic is required for Question Bank auto-scheduling.');const {data,error}=await supabase.from('question_banks').select('id,question,options,correct_option_index,explanation,topic,subject,language,channel_id,knowledge_base_topic_id,is_public,is_active').eq('is_active',true).eq('language',language).or(`user_id.eq.${userId},is_public.eq.true`).limit(500);if(error)throw error;const candidates=(data||[]).filter((q:any)=>{const qTopic=normalizeText(q.topic);const qSubject=normalizeText(q.subject);const topicExact=qTopic===cleanTopic;const subjectMatches=!cleanSubject||qSubject===cleanSubject;const channelMatches=!q.channel_id||q.channel_id===channelId;return topicExact&&subjectMatches&&channelMatches&&isValidQuestion(q);});const unique=new Map<string,any>();for(const q of candidates)unique.set(q.id,q);const exact=[...unique.values()];if(exact.length<safe){throw new Error(`Only ${exact.length} valid Question Bank questions match the exact topic "${topic}"${subject?` and subject "${subject}"`:''}${language?` in language "${language}"`:''}. Auto-scheduler will not mix unrelated topics.`);}return exact.sort(()=>Math.random()-0.5).slice(0,safe);}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response(null,{headers:corsHeaders});const supabaseUrl=Deno.env.get('SUPABASE_URL');const serviceRoleKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');const cronSecret=Deno.env.get('CRON_SECRET');const supplied=req.headers.get('x-cron-secret');const auth=req.headers.get('Authorization');const bearer=auth?.startsWith('Bearer ')?auth.slice(7).trim():'';let allowed=Boolean(cronSecret&&supplied===cronSecret)||Boolean(bearer&&serviceRoleKey&&bearer===serviceRoleKey);if(!allowed&&bearer){try{const authClient=createClient(supabaseUrl!,Deno.env.get('SUPABASE_ANON_KEY')!);const {data}=await authClient.auth.getUser(bearer);allowed=Boolean(data?.user);}catch{allowed=false;}}if(!allowed)return new Response(JSON.stringify({error:'Unauthorized'}),{status:401,headers:{...corsHeaders,'Content-Type':'application/json'}});try{if(!supabaseUrl||!serviceRoleKey)throw new Error('Missing Supabase configuration');const supabase=createClient(supabaseUrl,serviceRoleKey);let force=false,targetUserId:null|string=null,previewOnly=false;try{const body=await req.json();force=body.force===true;targetUserId=body.userId||null;previewOnly=body.previewOnly===true;}catch{}let settingsQuery=supabase.from('auto_schedule_settings').select('*, channels(name, telegram_channel_id, settings)').eq('enabled',true);if(targetUserId)settingsQuery=settingsQuery.eq('user_id',targetUserId);const {data:settings,error:settingsError}=await settingsQuery;if(settingsError)throw settingsError;if(!settings?.length)return new Response(JSON.stringify({success:true,message:'No enabled auto-schedules found'}),{headers:{...corsHeaders,'Content-Type':'application/json'}});const now=new Date();const matchingEntries:any[]=[];for(const setting of settings){if(!Array.isArray(setting.schedule_times)||!setting.schedule_times.length)continue;const tz=setting.timezone||'Asia/Kolkata';const times=[...setting.schedule_times].sort();if(force){const time=times[0]||'09:00';matchingEntries.push({setting,matchedTime:time,scheduledDate:computeScheduledDate(time,tz,now),slotIndex:0});continue;}for(let index=0;index<times.length;index++){const time=times[index];const scheduledDate=computeScheduledDate(time,tz,now);const diff=(now.getTime()-scheduledDate.getTime())/60000;if(diff>=-3&&diff<=35)matchingEntries.push({setting,matchedTime:time,scheduledDate,slotIndex:index});}}
if(!matchingEntries.length)return new Response(JSON.stringify({success:true,message:'No schedules to process',processed:0}),{headers:{...corsHeaders,'Content-Type':'application/json'}});const aiSettings=await getAISettings(supabase);let resolved:null|ResolvedAIProvider=null;try{resolved=resolveAIProvider(aiSettings);}catch{}const results:any[]=[];const dayNumber=Math.floor(now.getTime()/86400000);
for(const {setting,matchedTime,scheduledDate,slotIndex} of matchingEntries){try{if(!force){const from=new Date(scheduledDate.getTime()-20*60000).toISOString();const to=new Date(scheduledDate.getTime()+20*60000).toISOString();const {data:existing}=await supabase.from('scheduled_telegram_posts').select('id').eq('channel_id',setting.channel_id).gte('scheduled_time',from).lte('scheduled_time',to).in('status',['pending','processing','sent']).limit(1);if(existing?.length){results.push({channel_id:setting.channel_id,success:true,skipped:true,reason:`Already created for ${matchedTime}`});continue;}}
const {data:userPromptData}=await supabase.from('user_ai_system_prompts').select('system_prompt').eq('user_id',setting.user_id).maybeSingle();setting.userSystemPrompt=userPromptData?.system_prompt||'';let finalTopic='';let kbTopicContext='';let kbTopicInstructions='';let kbTopic:any=null;
const selectedIds=Array.isArray(setting.knowledge_base_topic_ids)?setting.knowledge_base_topic_ids.filter(Boolean):[];
if(setting.source_type==='knowledge_base'){let q=supabase.from('knowledge_base_topics').select('*').eq('user_id',setting.user_id);if(setting.channel_id)q=q.or(`channel_id.eq.${setting.channel_id},channel_id.is.null`);if(selectedIds.length)q=q.in('id',selectedIds);const {data:kbTopics,error:kbError}=await q;if(kbError)throw kbError;const available=(kbTopics||[]).filter((t:any)=>!t.channel_id||t.channel_id===setting.channel_id);if(!available.length)throw new Error('Knowledge Base source selected but no matching Knowledge Base topics are configured for this channel.');const ordered=[...available].sort((a:any,b:any)=>String(a.id).localeCompare(String(b.id)));kbTopic=ordered[(dayNumber*Math.max(setting.schedule_times?.length||1,1)+slotIndex)%ordered.length];finalTopic=kbTopic.topic||kbTopic.topic_name||'';if(!finalTopic)throw new Error('Selected Knowledge Base topic is missing a topic name.');kbTopicContext=[`Topic: ${finalTopic}`,kbTopic.subject?`Subject: ${kbTopic.subject}`:'',kbTopic.description?`Description: ${kbTopic.description}`:'',kbTopic.exam?`Target Exam: ${kbTopic.exam}`:'',kbTopic.grade?`Grade: ${kbTopic.grade}`:''].filter(Boolean).join('\n');kbTopicInstructions=kbTopic.ai_instructions||'';}
if(!finalTopic){const custom=Array.isArray(setting.topics)?setting.topics.filter(Boolean):[];finalTopic=custom.length?custom[(dayNumber*Math.max(setting.schedule_times?.length||1,1)+slotIndex)%custom.length]:rotatedTopic(setting.channel_id,slotIndex,dayNumber);}
const count=Math.max(1,Math.min(setting.questions_per_post||5,50));const language=setting.language||'bn';let questions:any[]=[];let sourceUsed=setting.source_type;
if(setting.source_type==='question_bank'){questions=await fetchQuestionBankQuestions(supabase,setting.user_id,setting.channel_id,count,finalTopic,kbTopic?.subject,language);}
else if(setting.source_type==='knowledge_base'){if(!resolved?.apiKey)throw new Error('AI provider is not configured for Knowledge Base generation.');const aiGenerated=await generateAIQuiz(setting,finalTopic,aiSettings,resolved,{kbTopicContext,kbTopicInstructions});questions=aiGenerated?.questions||[];}
if(!questions.length&&setting.source_type!=='question_bank'&&resolved?.apiKey){const aiGenerated=await generateAIQuiz(setting,finalTopic,aiSettings,resolved,{kbTopicContext,kbTopicInstructions});questions=aiGenerated?.questions||[];sourceUsed='ai_generated';}
if(!questions.length)throw new Error(`No questions available for topic "${finalTopic}".`);const quizData={topic:finalTopic,language,questions:questions.map((q:any,i:number)=>({id:i+1,question:q.question,options:q.options,correct_option_index:q.correct_option_index,explanation:q.explanation||''})),metadata:{difficulty:'medium',generated_at:new Date().toISOString(),source:sourceUsed,language,provider:resolved?.provider||'question_bank',model:resolved?.model||'question_bank',question_bank_topic:finalTopic,topic_lock:true}};if(previewOnly){results.push({channel_id:setting.channel_id,success:true,preview:quizData});continue;}const {error:insertError}=await supabase.from('scheduled_telegram_posts').insert({user_id:setting.user_id,chat_id:setting.channels?.telegram_channel_id||setting.channel_id,channel_id:setting.channel_id,quiz_data:quizData,scheduled_time:scheduledDate.toISOString(),status:'pending'});if(insertError?.code==='23505'){results.push({channel_id:setting.channel_id,success:true,skipped:true,reason:'Duplicate prevented'});continue;}if(insertError)throw insertError;results.push({channel_id:setting.channel_id,success:true,scheduled_time:scheduledDate.toISOString(),question_count:quizData.questions.length,topic:finalTopic,source:sourceUsed});fetch(`${supabaseUrl}/functions/v1/process-scheduled-posts`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${serviceRoleKey}`},body:JSON.stringify({triggered_by:'auto_schedule_generator',force})}).catch(()=>{});
}catch(error){console.error('[process-auto-schedule] Channel failed:',setting.channel_id,error);results.push({channel_id:setting.channel_id,success:false,error:error instanceof Error?error.message:String(error)});}}
return new Response(JSON.stringify({success:true,processed:matchingEntries.length,results}),{headers:{...corsHeaders,'Content-Type':'application/json'}});}catch(error){return new Response(JSON.stringify({error:error instanceof Error?error.message:String(error)}),{status:500,headers:{...corsHeaders,'Content-Type':'application/json'}});}});
async function generateAIQuiz(setting:any,topic:string,aiSettings:AISettings,resolved:ResolvedAIProvider,ctx:any){const count=Math.max(1,Math.min(setting.questions_per_post||5,50));const language=setting.language||'bn';const languageRule=language==='bn'?'Write questions, options and explanations in Bengali. Widely used English acronyms, names and units may stay in Latin script.':language==='hi'?'Write questions, options and explanations in Hindi (Devanagari). Widely used English acronyms, names and units may stay in Latin script.':'Write all content in clear English.';const systemPrompt=composeTelePostSystemPrompt({platformInstructions:aiSettings.system_prompt,userSystemPrompt:setting.userSystemPrompt||'',featureInstructions:setting.custom_prompt||'',knowledgeBaseInstructions:ctx.kbTopicInstructions||'',outputRequirements:`You are an expert competitive-exam question setter. ${languageRule} Generate exactly ${count} MCQs strictly about "${topic}". Every question must be directly relevant to this exact topic. Do not drift into other subjects or topics. Each question must have exactly four plausible options and one correct answer. Output only JSON.`});const userPrompt=`You MUST generate questions only for this exact topic. ${ctx.kbTopicContext?`Authoritative topic context:\n${ctx.kbTopicContext}\n\n`:''}Reject any idea that is outside the selected topic. Return exactly {"questions":[{"question":"string","options":["string","string","string","string"],"correct_option_index":0,"explanation":"string"}]}`;let lastError:Error|null=null;let feedback='';for(let attempt=1;attempt<=3;attempt++){try{const text=await chatCompletion({resolved,messages:[{role:'system',content:`${systemPrompt}${feedback?`\nPrevious output failed validation: ${feedback}`:''}`},{role:'user',content:userPrompt}],temperature:aiSettings.temperature??0.7,maxTokens:Math.min(8192,800+count*420),timeoutMs:90000,appTitle:'TelePost Auto Schedule'});const quiz=parseJsonObject(text) as any;const valid=Array.isArray(quiz?.questions)?quiz.questions.filter(isValidQuestion):[];if(valid.length!==count){feedback=`Expected exactly ${count} valid questions, received ${valid.length}.`;continue;}return {...quiz,questions:valid};}catch(e){lastError=e instanceof Error?e:new Error(String(e));feedback=lastError.message;}}throw lastError||new Error('Failed to generate a valid scheduled quiz.');}