// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-channels.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_channels_default = defineTool({
  name: "list_channels",
  title: "List Telegram channels",
  description: "List the signed-in user's Telegram channels configured in TelePost.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("channels").select("id, name, telegram_channel_id, description, created_at").order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { channels: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-posts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_posts_default = defineTool2({
  name: "list_posts",
  title: "List Telegram posts",
  description: "List the signed-in user's Telegram posts, optionally filtered by status (draft, scheduled, posted, failed).",
  inputSchema: {
    status: z.enum(["draft", "scheduled", "posted", "failed"]).optional().describe("Optional status filter."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("telegram_posts").select("id, channel_id, content, status, scheduled_at, posted_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-post.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_post_default = defineTool3({
  name: "create_post",
  title: "Create Telegram post (draft or scheduled)",
  description: "Create a new Telegram post for the signed-in user. Provide channel_id and content. Optionally set scheduled_at (ISO timestamp) to schedule it; otherwise it is saved as a draft.",
  inputSchema: {
    channel_id: z2.string().uuid().describe("Target channel UUID from list_channels."),
    content: z2.string().min(1).describe("Post text/content."),
    scheduled_at: z2.string().datetime().optional().describe("Optional ISO timestamp to schedule the post.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ channel_id, content, scheduled_at }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("telegram_posts").insert({
      user_id: ctx.getUserId(),
      channel_id,
      content,
      status: scheduled_at ? "scheduled" : "draft",
      scheduled_at: scheduled_at ?? null
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Post created (${data.id})` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-quizzes.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_quizzes_default = defineTool4({
  name: "list_quizzes",
  title: "List generated quizzes",
  description: "List the signed-in user's recently generated quizzes.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("quizzes").select("id, topic, difficulty, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { quizzes: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cazrdevenbxdjussycfj";
var mcp_default = defineMcp({
  name: "telepost-mcp",
  title: "TelePost",
  version: "0.1.0",
  instructions: "Tools for TelePost: manage Telegram channels, view/create Telegram posts, and list generated quizzes for the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_channels_default, list_posts_default, create_post_default, list_quizzes_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
